name: relabs

services:
  test:
    container_name: test
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    
    volumes:
      - db_test:/var/lib/postgresql/data

  development:
    container_name: development
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db_dev:/var/lib/postgresql/data

  app:
    container_name: backend
    image: ruby
    ports: 
      - 4567:4567
    volumes:
      - .:/app
      - gems:/usr/local/bundle/
    tty: true
    command: bash -c "cd app && bundle install && rerun server.rb"
    environment:
      - REDIS_URL=redis://redis:6379/0
  
  sidekiq:
    container_name: sidekiq
    image: ruby
    volumes:
      - .:/app
      - gems:/usr/local/bundle/
    ports: []
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: bash -c "cd app && sidekiq -r ./jobs/import_from_csv_job.rb"

  redis:
    container_name: redis
    image: redis

volumes:
  gems:
  db_test:
  db_dev: