name: relabs

services:
  test:
    container_name: test
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    
    volumes:
      - db_test:/var/lib/postgresql/data

  development:
    container_name: development
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db_dev:/var/lib/postgresql/data

  app:
    container_name: backend
    image: ruby
    ports: 
      - 4567:4567
    volumes:
      - .:/app
      - gems:/usr/local/bundle/
    tty: true

volumes:
  gems:
  db_test:
  db_dev: