name: relabs

services:
  app:
    image: ruby
    ports: 
      - 4567:4567
    networks:
      - rebaselab
    volumes:
      - .:/app
      - gems:/usr/local/bundle/
    tty: true
    container_name: backend
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5434:5432
    networks:
      - rebaselab
    volumes:
      - db:/var/lib/postgresql/data
    container_name: development
  db-test:
    image: postgres
    restart: always
    environment:
      - POSTGRES_TEST_DB=test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5433
    networks:
      - rebaselab
    volumes:
      - db-test:/var/lib/postgresql/data
    container_name: test


volumes:
  gems:
  db:
  db-test:

networks:
  rebaselab: {}