development:
  host: development
  database: development
  username: user
  password: password

test:
  host: test
  database: test
  username: user
  password: password

service:
  host: test
  database: postgres
  username: user
  password: password